name: Dependency Updates

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual trigger

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
    - name: Install dependencies
      run: npm ci
      
    - name: Check for updates
      id: updates
      run: |
        npm outdated --json > outdated.json || true
        if [ -s outdated.json ]; then
          echo "updates_available=true" >> $GITHUB_OUTPUT
          echo "Updates available:"
          cat outdated.json
        else
          echo "updates_available=false" >> $GITHUB_OUTPUT
          echo "No updates available"
        fi
        
    - name: Update dependencies
      if: steps.updates.outputs.updates_available == 'true'
      run: |
        # Update patch and minor versions only
        npm update
        
    - name: Run tests after update
      if: steps.updates.outputs.updates_available == 'true'
      run: |
        npm run build
        npm run lint
        
    - name: Create PR for dependency updates
      if: steps.updates.outputs.updates_available == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        BRANCH_NAME="dependency-updates/$(date +%Y-%m-%d)"
        
        # Check if there are changes
        if git diff --quiet package-lock.json; then
          echo "No dependency changes to commit"
          exit 0
        fi
        
        # Create and switch to new branch
        git checkout -b $BRANCH_NAME
        
        # Commit changes
        git add package-lock.json
        git commit -m "chore: update dependencies $(date +%Y-%m-%d)"
        
        # Push branch
        git push origin $BRANCH_NAME
        
        # Create PR
        gh pr create \
          --title "chore: Update dependencies $(date +%Y-%m-%d)" \
          --body "Automated dependency updates. Please review and merge if tests pass." \
          --base develop \
          --head $BRANCH_NAME